#!/usr/bin/env python3
"""Gzip web/dist and generate the C asset table embedded into the firmware.

Run at CMake configure time. Prints the gzipped file paths, one per line, for EMBED_FILES.
"""
import argparse
import gzip
import hashlib
import pathlib
import re
import sys

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".webp": "image/webp",
    ".ico": "image/x-icon",
    ".woff2": "font/woff2",
    ".txt": "text/plain; charset=utf-8",
    ".map": "application/json; charset=utf-8",
}


def symbol(name: str) -> str:
    """Mirror the mangling esp-idf's EMBED_FILES applies to the file name."""
    return "_binary_" + re.sub(r"[^0-9a-zA-Z]", "_", name)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dist", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--source", required=True)
    args = ap.parse_args()

    dist = pathlib.Path(args.dist)
    outdir = pathlib.Path(args.outdir)
    if not dist.is_dir():
        sys.stderr.write(
            f"\nERROR: {dist} is missing.\n"
            "The web UI is embedded into the firmware and must be built first:\n"
            "    cd web && npm ci && npm run build\n\n"
        )
        return 1

    files = sorted(p for p in dist.rglob("*") if p.is_file())
    if not files:
        sys.stderr.write(f"\nERROR: {dist} is empty; run `npm run build` in web/.\n\n")
        return 1

    outdir.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256()
    entries = []

    for path in files:
        rel = path.relative_to(dist).as_posix()
        raw = path.read_bytes()
        digest.update(rel.encode())
        digest.update(raw)
        # mtime=0 keeps the gzip byte-identical across builds so ccache and the ETag stay stable.
        packed = gzip.compress(raw, compresslevel=9, mtime=0)
        flat = re.sub(r"[^0-9a-zA-Z.]", "_", rel) + ".gz"
        (outdir / flat).write_bytes(packed)
        entries.append(
            (rel, flat, CONTENT_TYPES.get(path.suffix, "application/octet-stream"), len(packed))
        )

    build_hash = digest.hexdigest()[:16]

    src = [
        "/* Generated by components/webui/gen_assets.py. Do not edit. */",
        '#include "webui.h"',
        "",
    ]
    for _, flat, _ct, _sz in entries:
        sym = symbol(flat)
        src.append(f'extern const uint8_t {sym}_start[] asm("{sym}_start");')
    src.append("")
    src.append("const webui_asset_t webui_assets[] = {")
    for rel, flat, ct, size in entries:
        # The size is emitted as a literal: `_end - _start` is not a constant expression, so it
        # cannot initialise a static table.
        src.append(f'    {{"/{rel}", "{ct}", {symbol(flat)}_start, {size}}},')
    src.append("};")
    src.append("")
    src.append(f"const size_t webui_asset_count = {len(entries)};")
    src.append(f'const char webui_asset_hash[] = "{build_hash}";')
    src.append("")

    pathlib.Path(args.source).write_text("\n".join(src))
    for _, flat, _ct, _sz in entries:
        print(outdir / flat)
    return 0


if __name__ == "__main__":
    sys.exit(main())
